SELECT H.HACKER_ID, H.NAME, COUNT(C.CHALLENGE_ID) AS TOTAL 
FROM HACKERS H JOIN CHALLENGES C 
    ON H.HACKER_ID = C.HACKER_ID
    GROUP BY H.HACKER_ID, H.NAME
    HAVING 
        TOTAL = (SELECT COUNT(D.CHALLENGE_ID) AS MAX_CNT FROM CHALLENGES D GROUP BY D.HACKER_ID ORDER BY MAX_CNT DESC LIMIT 1)
        OR 
        TOTAL IN (SELECT DISTINCT D_CNT AS c_unique FROM (SELECT H1.HACKER_ID, H1.NAME, COUNT(C1.CHALLENGE_ID) AS D_CNT FROM HACKERS H1 JOIN CHALLENGES C1 ON H1.HACKER_ID = C1.HACKER_ID GROUP BY H1.HACKER_ID, H1.NAME) counts
        GROUP BY D_CNT
        HAVING COUNT(D_CNT) = 1)        
ORDER BY TOTAL DESC, H.HACKER_ID ASC; 