SELECT CASE 
    WHEN G.GRADE > 7 THEN CONCAT(S.NAME, ' ', G.GRADE, ' ', S.MARKS) 
    ELSE CONCAT("NULL ", G.GRADE, ' ', S.MARKS) 
    END 
FROM STUDENTS S JOIN GRADES G ON S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK ORDER BY G.GRADE DESC, S.NAME ASC, S.MARKS ASC ;