SELECT H.HACKER_ID, H.NAME 
FROM HACKERS H JOIN SUBMISSIONS S 
    ON H.HACKER_ID = S.HACKER_ID 
JOIN CHALLENGES C
    ON C.CHALLENGE_ID = S.CHALLENGE_ID
JOIN DIFFICULTY D
    ON D.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL
WHERE S.SCORE = D.SCORE
GROUP BY H.HACKER_ID, H.NAME 
HAVING COUNT(H.HACKER_ID) > 1 
ORDER BY COUNT(H.HACKER_ID) DESC, H.HACKER_ID ASC;