SELECT C.COMPANY_CODE, C.FOUNDER, 
COUNT(DISTINCT LM.LEAD_MANAGER_CODE), 
COUNT(DISTINCT SM.SENIOR_MANAGER_CODE), 
COUNT(DISTINCT M.MANAGER_CODE), 
COUNT(DISTINCT E.EMPLOYEE_CODE)
FROM COMPANY AS C, LEAD_MANAGER AS LM, SENIOR_MANAGER AS SM, MANAGER AS M, EMPLOYEE AS E 
WHERE LM.COMPANY_CODE = C.COMPANY_CODE 
AND SM.LEAD_MANAGER_CODE = LM.LEAD_MANAGER_CODE 
AND M.SENIOR_MANAGER_CODE = SM.SENIOR_MANAGER_CODE 
AND E.MANAGER_CODE = M.MANAGER_CODE 
GROUP BY C.COMPANY_CODE, C.FOUNDER ORDER BY C.COMPANY_CODE;
